name: Create and publish release

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_TOKEN }}
    - name: Zip folder
      id: zip_folder
      run: zip -r MultiHustle.zip MultiHustle/
    - name: Create release
      id: create_release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        title: ${{ github.ref }}
    - name: Upload release asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./MultiHustle.zip
        asset_name: MultiHustle.zip
        asset_content_type: application/zip
