name: Create and publish release

on:
 push:
   branches: [ main ]

jobs:
 build-and-release:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
     with:
       token: ${{ secrets.GIT_TOKEN }}
   - name: Zip folder
     id: zip_folder
     run: zip -r MultiHustle.zip MultiHustle/
   - name: Get latest release version
     id: get_latest_version
     run: |
       LATEST_VERSION=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
       echo "LATEST_VERSION=${LATEST_VERSION}"
   - name: Increment release version
     id: increment_version
     run: |
       VERSION_NUMBER=$(echo "${LATEST_VERSION}" | sed 's/^v//')
       NEW_VERSION_NUMBER=$((VERSION_NUMBER + 1))
       echo "NEW_VERSION_NUMBER=v${NEW_VERSION_NUMBER}"
   - name: Create release
     id: create_release
     uses: ncipollo/release-action@v1
     with:
       token: ${{ secrets.GIT_TOKEN }}
       tag: v${{ steps.increment_version.outputs.NEW_VERSION_NUMBER }}
       artifacts: ./MultiHustle.zip
       makeLatest: true
