name: Create and publish release

on:
  push:
    paths:
      - 'version.txt'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_TOKEN }}
    - name: Get version
      run: |
       echo "$(cat version.txt)" >> $GITHUB_ENV
       echo "Version: ${{ env.VERSION }}"
    - name: Zip folder
      id: zip_folder
      run: zip -r MultiHustle.zip MultiHustle/
    - name: Create release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GIT_TOKEN }}
        tag: v${{ env.VERSION }}
        artifacts: ./MultiHustle.zip
        makeLatest: true
