name: Create and publish release

on:
  push:
    paths:
      - 'version.txt'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_TOKEN }}
    - name: Zip folder
      id: zip_folder
      run: zip -r MultiHustle.zip MultiHustle/
    - name: Create tag
      run: git tag -a v$(cat version.txt) && git push origin v$(cat version.txt)
    - name: Create release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GIT_TOKEN }}
        tag: v$(cat version.txt)
        artifacts: ./MultiHustle.zip
        makeLatest: true
