name: Create and publish release

on:
 push:
   branches: [ main ]

jobs:
 build-and-release:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
     with:
       token: ${{ secrets.GIT_TOKEN }}
   - name: Get latest release tag
     id: get_latest_release_tag
     run: |
         latest_release_tag=$(git describe --tags --abbrev=0)
         echo "Latest release tag: $latest_release_tag"
   - name: Increment version number
     id: increment_version_number
     run: |
         major=$(echo $latest_release_tag | cut -d. -f1)
         minor=$(echo $latest_release_tag | cut -d. -f2)
         patch=$(echo $latest_release_tag | cut -d. -f3)
         new_version_number="$major.$((minor + 1)).$patch"
         echo "New version number: $new_version_number"
   - name: Create release
     id: create_release
     uses: elgohr/Github-Release-Action@v5
     env:
       GH_TOKEN: ${{ secrets.GIT_TOKEN }}
     with:
       title: "v${{ steps.increment_version_number.outputs.new_version_number }}"
